### ISSUE TITLE
Make the `perform` closure return type more readable

### ISSUE THREAD

**Issue by dalu93** [dalu93/Each#6]
Actually the return type is `Bool`

``` swift
timer.perform {
    // return `true` if you want to stop the timer, otherwise `false` to continue
}
```

In an implemented way where we want to stop the timer after doing `something()`, the code below isn't readable by other developers

``` swift
timer.perform {
    self.something()
    return true    // what does true mean? To continue it or to stop it?
}
```

A better way could be to declare an enum `NextStep` (as mentioned by @DeveloperPans) which encapsulates better the return type's meaning

``` swift
enum NextStep {

    case stop
    case `continue`
}
```

Which has a `fileprivate` extension that converts the enum to a `Bool` for the perform closure.
The final result for the user will be

``` swift
timer.perform {
    self.something()
    return .stop/.continue
}
```

**Comment by sjoness** [comment]
👍

**Comment by MrPans** [comment]
👍
