### ISSUE TITLE
 'seconds' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by leminhtuan2015** [dalu93/Each#8]
![screen shot 2016-10-25 at 11 52 46 pm](https://cloud.githubusercontent.com/assets/4700102/19695633/293a39fe-9b0e-11e6-8851-6966f7338bde.png)

 'seconds' is inaccessible due to 'internal' protection level

Please help!!!

**Comment by ssalatic** [comment]
I'm having the same issue

**Comment by dalu93** [comment]
Working on it, sorry guys. It will be fixed on `1.1.0` that will be released soon today

**Comment by dalu93** [comment]
@leminhtuan2015 @ssalatic version 1.1.0 is released on Cocoapods

**Comment by leminhtuan2015** [comment]
@dalu93 Thank you so much, 1.1.0 That working so great!
